config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :path => '', :path_names => { :sign_in => "admin"}
  root 'home#index'
  resources :posts
  resources :tags, only: [:show]

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  validates :title, :content, :embed_code, presence: true

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings

  def to_param
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @musicPosts = Post.where("category = 'Music'").order(created_at: :desc)
    @lessonPosts = Post.where("category = 'Lesson'").order(created_at: :desc)
    @posts = {musicPosts: @musicPosts, lessonPosts: @lessonPosts}
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def default_serializer_options
    {root: false}
  end

  respond_to :json, :html

  def index
    @musicPosts = Post.where("category = 'Music'").order(created_at: :desc)
    @lessonPosts = Post.where("category = 'Lesson'").order(created_at: :desc)
    @posts = {musicPosts: @musicPosts, lessonPosts: @lessonPosts}
    respond_with @posts
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.content = @post.content.gsub(/\r\n/, '<br>')
    @post.embed_code = @post.embed_code.gsub(/width=\"560\"/, "width=\"100%\"").gsub(/height=\"450\"/, "height=\"315\"")

    if @post.save
      flash[:notice] = "Post saved!"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    # respond_with @post
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path, notice: "You have updated the post #{@post.title}"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end


  private

  def post_params
    params.require(:post).permit(:title, :content, :embed_code, :category, :created_at, :all_tags)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find_by_name(params[:id])
    @posts = @tag.posts.order(created_at: :desc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="page-body">
  <div id="shim"></div>
  <div id="landing-page" class="section-box">
    <% if user_signed_in? %>
    <div id="logout-button">
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      <%= link_to('New Post', new_post_path) %>
    </div>
    <% end %>
    <div id="name-banner">
      <h1>Jeremy Stoddard Carroll</h1>
      <h5>Musician, composer, & teacher</h5>
    </div>
    <div class="sectionButtons">
      <div id="buttonA">
        <div class="home-page-link btn-outline">
          <h3>Listen</h3>
          <i class="fa fa-fw fa-music"></i>
        </div>
      </div>
      <div id="buttonB">
        <div class="home-page-link btn-outline">
          <i class="fa fa-fw fa-thumbs-up"></i>
          <h3>Learn</h3>
        </div>
      </div>
    </div>
    <div id="footer">
      <ul class="list-inline">

       <li>
        <a href="" class="btn-outline soc-link"><i class="fa fa-fw fa-youtube fa-2x"></i></a>
      </li>
      <li>
        <a href="" class="btn-outline soc-link"><i class="fa fa-fw fa-soundcloud fa-2x"></i></a>
      </li>
      <li>
        <a href="" class="btn-outline soc-link"><i class="fa fa-fw fa-headphones fa-2x"></i></a>
      </li>
      <li>
        <a href="" class="btn-outline soc-link"><i class="fa fa-fw fa-google-plus fa-2x"></i></a>
      </li>

      <li>
        <a href="" class="btn-outline soc-link"><i class="fa fa-fw fa-twitter fa-2x"></i></a>
      </li>
      <li>
        <a href="" class="btn-outline soc-link"><i class="fa fa-fw fa-instagram fa-2x"></i></a>
      </li>

    </ul>
  </div>

</div>
<div id="sectionA" class="section-box">
  <div class="backBox">
    <a class="homeButton btn-outline soc-link"><i class="fa fa-fw fa-home fa-2x"></i></a>
    <a class="scrollup btn-outline soc-link"><i class="fa fa-fw fa-sort-up fa-2x"></i></a>
  </div>
  <h1 class="section-title">Music</h1>
  <hr><hr>
  <ul>
    <% @musicPosts.each do |post| %>
    <li>
      <%= render post %>
    </li>
    <% end %>
  </ul>
</div>
<div id="sectionB" class="section-box">
  <div class="backBox">
    <a class="homeButton btn-outline soc-link"><i class="fa fa-fw fa-home fa-2x"></i></a>
    <a class="scrollup btn-outline soc-link"><i class="fa fa-fw fa-sort-up fa-2x"></i></a>
  </div>
  <h1>Lessons</h1>
  <hr><hr>
  <ul>
    <% @lessonPosts.each do |post| %>
    <li>
      <%= render post %>
    </li>
    <% end %>
  </ul>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jeremycarrol</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="row-fluid">
  <%= form_for (@post), html: {:class => "form-horizontal"} do |f| %>

  <div class="col-md-6 col-md-offset-3">
    <% if @post.errors.any? %>
      <div class="bg-warning">
        This form has <%=pluralize(@post.errors.count, "error") %>.
      </div>
      <ul class="text-left">
        <% @post.errors.full_messages.each do |msg| %>
          <li>* <%= msg %> </li>
        <% end %>
      </ul>
    <% end %>

    <fieldset>
      <legend> New post </legend>

      <div class="control-group">
        <%= f.label :title, "Title" %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :content, 'Post Body' %>
        <div class="controls">
          <%= f.text_area :content %>
        </div>
      </div>
      <br>

      <div class="control-group">
        <%= f.label :embed_code, "Embed Media (youtube, soundcloud, bandcamp)" %>
        <div class="controls">
          <%= f.text_field :embed_code %>
        </div>
      </div>
      <br>

      <div class="control-group">
        <%= f.label :category, "Post type" %>
        <div class="controls">
          <%= f.collection_radio_buttons(
              :category, [['Lesson', 'Lesson'],['Music', 'Music']], :first, :last) %>
        </div>
      </div>
      <br>

      <div class="control-group">
        <%= f.label :all_tags, "tags (separate with comma)" %>
        <div class="controls">
          <%= f.text_field :all_tags %>
        </div>
      </div>
      <br>

      <div class="form-actions">
        <%= f.submit "Create post!", class: "btn btn-large btn-primary" %>
      </div>

    </fieldset>
  </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
  <div class="row">
    <!-- <div class="embedded_media col-md-8"><iframe width="560" height="315" src=<%= post.embed_code %> frameborder="0" allowfullscreen></iframe></div> -->
    <div data-id={{id}} class="post-title col-md-3 col-md-offset-1">
    <% if user_signed_in? %>
      <h2><%= link_to post.title, post_path(post) %></h2>
    <% else %>
      <h2><%= post.title %></h2>
    <% end %>
      <h5><%= post.created_at.strftime("%B %d, %Y @ %I:%M %p") %></h5>
      <h4>Tagged under:</h4>
      <ul class="tags">
      <% post.tags.each do |tag| %>
        <li class="tag">
          <%= button_to tag.name, tag_path(tag), method: "get", class: "btn-info btn btn-med" %>
        </li>
      <% end %>
      </ul>
      <br>
    </div>
    <div class="embedded_media col-md-6 col-md-offset-1 col-xs-10 col-xs-offset-1"><%= raw post.embed_code %></div>
    
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1 post-content">
      <p><%= raw post.content %></p>
    </div>
  </div>
</li>
<hr>
<br>

app/views/posts/edit.html.erb
<h2>edit post</h2>
<%= render 'form', post: @post %>

app/views/posts/new.html.erb
<% if !user_signed_in? %>
  <script type='text/javascript'>
  window.location.href = "/";
  </script>
<% end %>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% if user_signed_in? %>
  <!-- <div onclick="window.location+='/edit'">click to edit</div> -->
  <%= button_to "Edit Post", edit_post_path(@post), method: :get %>
  <%= button_to "Delete Post", post_path(@post), method: :delete %>
<% end %>

<%= render @post %>

app/views/tags/show.html.erb
<div id="page-body">
  <div id="shim"></div>
  <div id="tagSection" class="section-box">
    <div class="backBox">
    <a href="/" class="homeButton soc-link btn-outline"><i class="fa fa-fw fa-home fa-2x"></i></a>
      <a class="scrollup soc-link btn-outline"><i class="fa fa-fw fa-sort-up fa-2x"></i></a>
    </div>
    <h1 class="section-title">Tag: <%= @tag.name %></h1>
    <hr><hr>
    <ul>
      <% @posts.each do |post| %>
      <li>
        <%= render post %>
      </li>
      <% end %>
    </ul>
  </div>
</div>